### ISSUE TITLE
engagement task completion date is integer

### ISSUE THREAD

**Issue by jamesrayoub** [fivetran/dbt_hubspot_source#39]
Should be cast as timestamp

{"name": "completion_date", "datatype": dbt_utils.type_int()},

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jamesrayoub good catch and thanks for calling this out. I will open a PR today to reflect the correct casting.

Have you by chance noticed any other casting discrepancies as you have been using the package that I should include in the PR?

**Comment by jamesrayoub** [comment]
that's all I found so far

**Comment by jamesrayoub** [comment]
In our instance, the field is now being brought in as a string... not sure what happened as there are no recent release notes

**Comment by fivetran-joemarkiewicz** [comment]
@jamesrayoub I notice the field is still being brought in at the connector level as a string. As such, do you believe PR #40 is still relevant?

**Comment by jamesrayoub** [comment]
@fivetran-joemarkiewicz I think the best solution would be to do:

`{{ dbt_utils.safe_cast(completion_date, timestamp) }} as completion_timestamp`

That should attempt to cast the string as a timestamp but just return null if not. I've essentially done this in the downstream engagement task model

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @jamesrayoub! I just changed the macro to bring the datatype in originally as a string (since that changed) and added the safe_cast macro to the staging model to then cast correctly to a timestamp.

Thank you for the suggestion and bringing this up, I will try to have it reviewed soon and then be included in the next release.
