### ISSUE TITLE
Git merge artifacts in package docs

### ISSUE THREAD

**Issue by austin-stytch** [fivetran/dbt_hubspot_source#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hi - on https://hub.getdbt.com/fivetran/hubspot/latest/ there are git merge artifacts

<img width="582" alt="image" src="https://user-images.githubusercontent.com/101587420/188726158-b3981988-3418-4ff1-82f2-d4e1cfbde40c.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/101587420/188726199-97ca1d5a-35ec-405d-9bcd-0af63cdf6937.png">

### Expected behavior

no artifacts

### dbt Project configurations

n/a

### Package versions

n/a

### What database are you using dbt with?

snowflake

### dbt Version

****

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @austin-stytch thanks so much for opening this issue! It looks like another customer caught this as well and opened [PR #80](https://github.com/fivetran/dbt_hubspot/pull/80) to address this issue.

We have since merged that PR and are planning a new release soon. Those git artifacts in the README should be gone in the next hour!

**Comment by fivetran-joemarkiewicz** [comment]
The release is now live! Closing this issue as it has been resolved. Thanks again for flagging this for our team @austin-stytch 🎉
