### ISSUE TITLE
[Bug] missing source column causing model error

### ISSUE THREAD

**Issue by kcraig-ats** [fivetran/dbt_hubspot_source#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

 We're running into an error running `stg_hubspot__deal`.  The `property_closedate` column is the issue because it is not included in our instance of the `deal` source table. We have `hubspot__deal_pass_through_columns` enabled, which bypasses the macro CTE where those columns are staged. 

### Expected behavior

The staged columns created in the macro CTE would be used irrespective of the use of the `hubspot__deal_pass_through_columns`.

### dbt Project configurations

`hubspot__pass_through_all_columns: true`

### Package versions

```yml
package: fivetran/hubspot
version: [">=0.8.0", "<0.9.0"]
```

### What database are you using dbt with?

redshift

### dbt Version

1.3

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @kcraig-ats thanks for opening this issue. This is an interesting scenario 🤔.

I agree that it would be best if the `get_deal_macro` would be able to be used irrespective of the hubspot__pass_through_all_columns variable being set to `true`. However, the [get_deal_columns](https://github.com/fivetran/dbt_hubspot_source/blob/main/macros/get_deal_columns.sql) only includes a fraction of the fields. Therefore, if we used the macro, we would not be able to select **all** fields from your source table. In order to leverage the macro, we would need to include all the possible fields. Which is unfortunately not realistic due to the customizable nature of these HubSpot sources.

I am curious if you have any insight into why you do not have the `property_closedate` field in your source deal table? I was under the impression this was standard field that would represent the closed date for deals. Do you have a different field that represents this same value?

Regardless, you pose a valid bug and one we should address in the next release of the package. In the meantime, I will brainstorm with the team so viable avenues to ensure the package works when using the all column variable, while still ensuring the [required fields](https://github.com/fivetran/dbt_hubspot_source/blob/0853a039e5e953f848fa0172636b551cd03f7c74/models/stg_hubspot__deal.sql#L22-L25) are populated regardless of their presence in the source.

**Comment by kcraig-ats** [comment]
Hi @fivetran-joemarkiewicz - Thanks for responding so quickly! Yeah, my guess is this an edge case. The field is standard in HubSpot but only contains null data at the moment. My understanding is that the connector skips those fields.

**Comment by fivetran-jamie** [comment]
the fix for this should officially be in v0.9.0 of the package!
